# You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.
# Example 1:

# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        sum_s = 0
        sum_t = 0
        for ch in s:
            sum_s += ord(ch)
        for ch in t:
            sum_t += ord(ch)
        return (str(chr(sum_t - sum_s)))
